name: solrindexing
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - matplotlib>=3.1
  - numpy>=1.17
  - scipy>=1.2
  - netcdf4>=1.6.4
  - pyproj>=2.3
  - cartopy
  - pip
  - pysolr
  - xmltodict
  - python-dateutil
  - yaml
  - owslib
  - ipython
  - cython
  - shapely>=2.0
  - lxml
  - geojson
  - lxml
  - validators
  - certifi
  - urllib3
  - requests
  - python-dotenv