name: solrindexing
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - netcdf4>=1.6.4
  - pip
  - pysolr
  - python-dateutil
  - yaml
  - owslib
  - ipython
  - cython
  - shapely>=2.0
  - lxml
  - geojson
  - lxml
  - validators
  - certifi
  - urllib3
  - requests
  - python-dotenv
  - rdflib
