name: Docker build test python 3.9

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t solrindexer:latest .
     - name: Install solrindexer in docker image
      run: |
        docker run --rm solrindexer:latest

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel

    - name: Install Python package
      run: |
        pip install solrindexer -r requirements.txt || exit 1
